spring:
  application:
    name: luckycloud
  profiles:
    active: dev
  banner:
    location: classpath:static/banner.txt
  config:
    import:
      - optional:classpath:/application-common.yml
      - optional:classpath:/application-security.yml
      - optional:classpath:/application-blog.yml
      - optional:classpath:/application-web.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
server:
  port: 8080
